### ISSUE TITLE
tsd jsx with webpack

### ISSUE THREAD

**Issue by nathanvale** [wallabyjs/typescript-tsx-jsx#2]
Hi there,

I have really tried to get this to work with webpack and just dont seem to be getting anywhere.

tsx files are unable to be loaded.

I get errors like these

​`ModuleParseError: Module parse failed: ./src/shared/components/Counter/Counter.tsx Unexpected token (6:2)
​You may need an appropriate loader to handle this file type.`

Any help would be apprectaied as I would love to get this working with sinon, chai, enzyme and typescript.

Thanks!

``` javascript
'use strict';

var wallabyWebpack = require('wallaby-webpack');
var webpack = require('webpack');
var path = require('path');
var chai = require('chai');

var webpackPostprocessor = wallabyWebpack({

    entryPatterns: [
        'tests/karma.bundler.js',
        'tests/**/*.spec.js'//,
        //'src/**/*.js'
    ],
    externals: {
        "react": "React",
        'react/addons': true,
        'react/lib/ExecutionEnvironment': true,
        'react/lib/ReactContext': 'window'
    },
    resolve: {
        root: __dirname,
        extensions: ['', '.ts', '.tsx', '.js', '.jsx', '.json'],
        alias: {
            sinon: 'sinon/pkg/sinon.js'
        }
    },
    module: {

        noParse: [
            /\/sinon\.js/
        ],
        plugins: [
            new webpack.NormalModuleReplacementPlugin(/\.(html|gif|png|scss|css|sass)$/, 'node-noop')
        ],
        loaders: [
            {
                test: /sinon(\\|\/)pkg(\\|\/)sinon\.js/,
                loader: 'imports?define=>false,require=>false'
            },
            {
                test: /\.json$/,
                loader: 'json-loader'
            },
            {
                test: /\.less$/,
                loader:
                'style!css?sourceMap&-minimize&modules&importLoaders=1&sourceMap&localIdentName=[local]___[hash:base64:5]!postcss!less?outputStyle=expanded&sourceMap'
            },
            {
                test: /\.scss$/,
                loader: 'style!css?sourceMap&-minimize&modules&importLoaders=1&sourceMap&localIdentName=[local]___[hash:base64:5]!postcss!sass?outputStyle=expanded&sourceMap'
            },

        ],
    }
});


module.exports = function (wallaby) {


    return {
        debug: true,
        files: [
            { pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false },
            { pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false },
            { pattern: 'src/**/*.js*', load: false },
            { pattern: 'src/**/*.ts', load: false },
            { pattern: 'src/**/*.tsx', load: false },
            { pattern: 'src/**/*.html', load: false },
            { pattern: 'src/**/*.scss', load: false },
            { pattern: 'src/**/*.jpg', load: false },
        ],
        tests: [

            { pattern: 'tests/**/*.spec.tsx', load: false },
            { pattern: 'tests/**/*.spec.ts', load: false }

        ],
        preprocessors: {
            "**/*.js*": function (file) {
                return require("babel-core").transform(file.content, {
                    sourceMap: true,
                    presets: ["es2015", "stage-2", "react"],
                    plugins: ["jsx-control-statements"]
                });
            }
        },
        compilers: {
            '**/*.ts*': wallaby.compilers.typeScript({
                "module": "es6"
            }),
            "**/*.js*": wallaby.compilers.babel({ presets: ["es2015", "stage-2", "react"] })
        },

        postprocessor: webpackPostprocessor,

        testFramework: "mocha",
        bootstrap: function () {

            window.__moduleBundler.loadTests();

        }
    };
};
```

**Comment by ArtemGovorov** [comment]
Try removing `.ts` and `.tsx` files from your `resolve.extensions`. Wallaby copies them over to its cache to compile, then changes the extension to `.js` after compiling, but `.ts` and `.tsx` files are still around, and your order of extensions makes webpack to load them first - hence the error.

```
var webpackPostprocessor = wallabyWebpack({
  ...
  resolve: {
    ...
    extensions: ['', '.js', '.jsx', '.json'],
  }
  ...
}
```

**Comment by ArtemGovorov** [comment]
You'll also need to add the `tests/karma.bundler.js` file to your `files` list.

**Comment by nathanvale** [comment]
Thank heaps! i manged to get that all working and now running tests in visual studio code. Very cool.

I have one hurdle left...

I cant seem to get tests working that involve using enzyme and the render method. 6 of my 39 tests are failing.

If I run my tests through karma with npm test all 39 tests pass but through wallaby tests such as  these fail.
`const welcome = component.find('h4');
    console.log(welcome);
    expect(welcome).to.exist;
    expect(welcome.text()).to.match(/Welcome!/);`

I have put up my repo - you are welcome to have a look as it might be easier than me copying and pasting code.

https://github.com/nathanvale/reactjs-hackathon-kit

Thanks.

**Comment by ArtemGovorov** [comment]
Thanks for the repo. When I run your tests, I see few tests failing because of the  `RangeError: Maximum call stack size exceeded`. This is a known [PhanomJs + chai issue](https://github.com/wallabyjs/public/issues/141#issuecomment-179834833). It works in karma because you seem to run it in Chrome and the issue is PhantomJs specific (if you run your tests in PhantomJs with karma you'll get the same issue). You may fix it by adding this line to your `spec-helper`:

``` javascript
...
chai.use(sinonChai);
chai.use(chaiAsPromised);
chai.use(chaiEnzyme());
global.should = undefined; // <----
global.When = When;
global.Parse = parse;
global.chai = chai;
global.sinon = sinon;
global.expect = chai.expect;
global.should = chai.should();
...
```

Not related to the issue:
- You may remove the `{ pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false },` line from your `files` list, wallaby includes the polyfill automatically.
- You may also remove your[ `setup` function](https://wallabyjs.com/docs/config/bootstrap.html). It's just overwritten by its alias `bootstrap` and is not working at all (looks like you've taken it from some node.js tests project example).

**Comment by nathanvale** [comment]
Thanks mate. Awesome project and great support. Love the name of your project too.

For other's it would be great if you put a little tutorial up on your site that explains how to to a chai/sinon/tsx/webpack set up. I think this repo is just a node one.

There were a couple of gotchas like the resolve extensions caching and the very odd global.should = undefined; (all though not problems specific with wallaby.)

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update! I'll put together a sample project for the mentioned stack to make it easier for others.
